// Sample categories
export const categories = [
    {
        id: "1",
        name: "Electronics",
        slug: "electronics",
        icon: "💻",
        productCount: 15420,
        color: "#3b82f6",
    },
    {
        id: "2",
        name: "Gaming",
        slug: "gaming",
        icon: "🎮",
        productCount: 8730,
        color: "#8b5cf6",
    },
    {
        id: "3",
        name: "Home & Garden",
        slug: "home-garden",
        icon: "🏠",
        productCount: 12350,
        color: "#10b981",
    },
    {
        id: "4",
        name: "Health & Beauty",
        slug: "health-beauty",
        icon: "💄",
        productCount: 25600,
        color: "#ec4899",
    },
    {
        id: "5",
        name: "Groceries",
        slug: "groceries",
        icon: "🛒",
        productCount: 45200,
        color: "#f59e0b",
    },
    {
        id: "6",
        name: "Stationery",
        slug: "stationery",
        icon: "✏️",
        productCount: 9840,
        color: "#06b6d4",
    },
    {
        id: "7",
        name: "Baby & Kids",
        slug: "baby-kids",
        icon: "👶",
        productCount: 18900,
        color: "#f43f5e",
    },
    {
        id: "8",
        name: "Food & Drink",
        slug: "food-drink",
        icon: "🍫",
        productCount: 7650,
        color: "#84cc16",
    },
];

// Featured deals with real Amazon affiliate links
export const featuredDeals = [
    {
        id: "p1",
        name: "Ninja Blast Portable Blender, 530ml, Cordless Mini Blender",
        imageUrl: "/products/ninja-blender.jpg",
        currentPrice: 39.00,
        originalPrice: 49.99,
        retailer: "Amazon UK",
        dealScore: "good" as const,
        percentOff: 22,
        affiliateUrl: "https://amzn.to/3Zi9Z89",
    },
    {
        id: "p2",
        name: "Gillette Fusion5 Blades, Men's Shaving Refills Pack of 11",
        imageUrl: "/products/gillette-fusion5.jpg",
        currentPrice: 21.91,
        originalPrice: 26.99,
        retailer: "Amazon UK",
        dealScore: "good" as const,
        percentOff: 19,
        affiliateUrl: "https://amzn.to/4k4l1Yc",
    },
    {
        id: "p3",
        name: "Duracell Plus AA Batteries (12 Pack) - Alkaline 1.5V",
        imageUrl: "/products/duracell-aa.jpg",
        currentPrice: 8.39,
        originalPrice: 11.50,
        retailer: "Amazon UK",
        dealScore: "good" as const,
        percentOff: 27,
        affiliateUrl: "https://amzn.to/49D4IxQ",
    },
    {
        id: "p4",
        name: "Shark Steam Mop for Hard Floors with 2 Washable Pads",
        imageUrl: "/products/shark-steam-mop.jpg",
        currentPrice: 39.00,
        originalPrice: 69.99,
        retailer: "Amazon UK",
        dealScore: "great" as const,
        percentOff: 44,
        affiliateUrl: "https://amzn.to/4bNwsRF",
    },
    {
        id: "p5",
        name: "Lavazza Qualità Rossa, Ground Coffee, 12 Packs of 250g",
        imageUrl: "/products/lavazza-coffee.jpg",
        currentPrice: 41.95,
        originalPrice: 75.00,
        retailer: "Amazon UK",
        dealScore: "great" as const,
        percentOff: 44,
        affiliateUrl: "https://amzn.to/4qF2uUH",
    },
    {
        id: "p6",
        name: "Allevia Hayfever Allergy Tablets, 120mg Fexofenadine, 30 Tablets",
        imageUrl: "/products/allevia-hayfever.jpg",
        currentPrice: 6.87,
        originalPrice: 11.89,
        retailer: "Amazon UK",
        dealScore: "great" as const,
        percentOff: 42,
        affiliateUrl: "https://amzn.to/45sSDsw",
    },
    {
        id: "p7",
        name: "Voltarol Joint & Back Pain Relief 2.32% Gel, 50g",
        imageUrl: "/products/voltarol-gel.jpg",
        currentPrice: 8.54,
        originalPrice: 14.50,
        retailer: "Amazon UK",
        dealScore: "great" as const,
        percentOff: 41,
        affiliateUrl: "https://amzn.to/4r7vc07",
    },
    {
        id: "p8",
        name: "Andrex Complete Clean Toilet Roll 36 Rolls",
        imageUrl: "/products/andrex-toilet-roll.jpg",
        currentPrice: 17.00,
        originalPrice: 23.80,
        retailer: "Amazon UK",
        dealScore: "good" as const,
        percentOff: 29,
        affiliateUrl: "https://amzn.to/49TAc1z",
    },
    {
        id: "p9",
        name: "Deconovo Blackout Curtains, 46 x 54 Inch, Black, 2 Panels",
        imageUrl: "/products/deconovo-curtains.jpg",
        currentPrice: 10.37,
        originalPrice: 14.72,
        retailer: "Amazon UK",
        dealScore: "good" as const,
        percentOff: 30,
        affiliateUrl: "https://amzn.to/4biHZs2",
    },
    {
        id: "p10",
        name: "PERLESMITH TV Wall Bracket for 26-70 Inch TVs",
        imageUrl: "/products/perlesmith-bracket.jpg",
        currentPrice: 21.98,
        originalPrice: 34.99,
        retailer: "Amazon UK",
        dealScore: "good" as const,
        percentOff: 37,
        affiliateUrl: "https://amzn.to/4benInz",
    },
    {
        id: "p11",
        name: "TUMELLA Strongest Windproof Travel Umbrella, Compact",
        imageUrl: "/products/tumella-umbrella.jpg",
        currentPrice: 17.98,
        originalPrice: 29.99,
        retailer: "Amazon UK",
        dealScore: "great" as const,
        percentOff: 40,
        affiliateUrl: "https://amzn.to/4rxfMmn",
    },
    {
        id: "p12",
        name: "Blink Video Doorbell System, HD View, 2-Year Battery",
        imageUrl: "/products/blink-doorbell.jpg",
        currentPrice: 35.99,
        originalPrice: 59.99,
        retailer: "Amazon UK",
        dealScore: "great" as const,
        percentOff: 40,
        affiliateUrl: "https://amzn.to/3Zia8bH",
    },
];

// Sample retailers for the logo strip
export const retailers = [
    { name: "Amazon UK", logo: "/retailers/amazon.svg" },
    { name: "Currys", logo: "/retailers/currys.svg" },
    { name: "Argos", logo: "/retailers/argos.svg" },
    { name: "Tesco", logo: "/retailers/tesco.svg" },
    { name: "Sainsbury's", logo: "/retailers/sainsburys.svg" },
    { name: "John Lewis", logo: "/retailers/johnlewis.svg" },
    { name: "Asda", logo: "/retailers/asda.svg" },
    { name: "AO.com", logo: "/retailers/ao.svg" },
];

// Stats for the hero section
export const stats = [
    { label: "Products Tracked", value: "500K+" },
    { label: "UK Retailers", value: "25+" },
    { label: "Price Updates", value: "Daily" },
    { label: "Price History", value: "5 Years" },
];
