// Sample categories
export const categories = [
    {
        id: "1",
        name: "Electronics",
        slug: "electronics",
        icon: "💻",
        productCount: 15420,
        color: "#3b82f6",
    },
    {
        id: "2",
        name: "Gaming",
        slug: "gaming",
        icon: "🎮",
        productCount: 8730,
        color: "#8b5cf6",
    },
    {
        id: "3",
        name: "Home & Garden",
        slug: "home-garden",
        icon: "🏠",
        productCount: 12350,
        color: "#10b981",
    },
    {
        id: "4",
        name: "Health & Beauty",
        slug: "health-beauty",
        icon: "💄",
        productCount: 25600,
        color: "#ec4899",
    },
    {
        id: "5",
        name: "Groceries",
        slug: "groceries",
        icon: "🛒",
        productCount: 45200,
        color: "#f59e0b",
    },
    {
        id: "6",
        name: "Stationery",
        slug: "stationery",
        icon: "✏️",
        productCount: 9840,
        color: "#06b6d4",
    },
    {
        id: "7",
        name: "Baby & Kids",
        slug: "baby-kids",
        icon: "👶",
        productCount: 18900,
        color: "#f43f5e",
    },
    {
        id: "8",
        name: "Food & Drink",
        slug: "food-drink",
        icon: "🍫",
        productCount: 7650,
        color: "#84cc16",
    },
];

// Featured deals with real Amazon affiliate links
export const featuredDeals = [
    {
        id: "p1",
        name: "BIC Twin Lady Razor Pouch 5",
        imageUrl: "https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=400&h=400&fit=crop",
        currentPrice: 2.49,
        originalPrice: 3.99,
        retailer: "Amazon UK",
        dealScore: "good" as const,
        percentOff: 38,
        affiliateUrl: "https://amzn.to/4jXOBOT",
    },
    {
        id: "p2",
        name: "Faber-Castell Latex-Free Eraser For Ink/Pencil",
        imageUrl: "https://images.unsplash.com/photo-1589810635657-232948472d98?w=400&h=400&fit=crop",
        currentPrice: 1.29,
        originalPrice: 1.99,
        retailer: "Amazon UK",
        dealScore: "good" as const,
        percentOff: 35,
        affiliateUrl: "https://amzn.to/4b7yrQC",
    },
    {
        id: "p3",
        name: "Red Telephone Box Breakfast Tea 6 Teabag Carton",
        imageUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=400&fit=crop",
        currentPrice: 3.99,
        originalPrice: 5.49,
        retailer: "Amazon UK",
        dealScore: "good" as const,
        percentOff: 27,
        affiliateUrl: "https://amzn.to/49UvGQl",
    },
    {
        id: "p4",
        name: "Colgate Extra Clean Medium Toothbrush Pack of 3",
        imageUrl: "https://images.unsplash.com/photo-1559650656-5d1d361ad10e?w=400&h=400&fit=crop",
        currentPrice: 2.99,
        originalPrice: 4.49,
        retailer: "Amazon UK",
        dealScore: "good" as const,
        percentOff: 33,
        affiliateUrl: "https://amzn.to/3ZsfGjE",
    },
    {
        id: "p5",
        name: "Zebra Z-Grip Black Ballpoint Pen Multipack",
        imageUrl: "https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400&h=400&fit=crop",
        currentPrice: 4.49,
        originalPrice: 6.99,
        retailer: "Amazon UK",
        dealScore: "good" as const,
        percentOff: 36,
        affiliateUrl: "https://amzn.to/4jVRM9Q",
    },
    {
        id: "p6",
        name: "NIVEA Soothing Care Aloe Vera Hand Cream 75ml",
        imageUrl: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=400&fit=crop",
        currentPrice: 2.25,
        originalPrice: 3.49,
        retailer: "Amazon UK",
        dealScore: "good" as const,
        percentOff: 36,
        affiliateUrl: "https://amzn.to/3Lt9rcf",
    },
    {
        id: "p7",
        name: "Kleenex Balsam Pocket Tissues 8 Pack",
        imageUrl: "https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=400&h=400&fit=crop",
        currentPrice: 2.99,
        originalPrice: 4.25,
        retailer: "Amazon UK",
        dealScore: "good" as const,
        percentOff: 30,
        affiliateUrl: "https://amzn.to/3NAxQgu",
    },
    {
        id: "p8",
        name: "Swizzels Squashies Strawberry & Cream 140g",
        imageUrl: "https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=400&h=400&fit=crop",
        currentPrice: 1.00,
        originalPrice: 1.50,
        retailer: "Amazon UK",
        dealScore: "good" as const,
        percentOff: 33,
        affiliateUrl: "https://amzn.to/4rsCNXB",
    },
    {
        id: "p9",
        name: "Halls Soothers Honey & Lemon Lozenges 45g",
        imageUrl: "https://images.unsplash.com/photo-1471943311424-646960669fbc?w=400&h=400&fit=crop",
        currentPrice: 1.25,
        originalPrice: 1.89,
        retailer: "Amazon UK",
        dealScore: "good" as const,
        percentOff: 34,
        affiliateUrl: "https://amzn.to/4jZC1Pg",
    },
    {
        id: "p10",
        name: "Johnson's Baby Cotton Buds 200 Pack",
        imageUrl: "https://images.unsplash.com/photo-1584949091598-c31daaaa4aa9?w=400&h=400&fit=crop",
        currentPrice: 1.75,
        originalPrice: 2.49,
        retailer: "Amazon UK",
        dealScore: "good" as const,
        percentOff: 30,
        affiliateUrl: "https://amzn.to/4jRkcl7",
    },
];

// Sample retailers for the logo strip
export const retailers = [
    { name: "Amazon UK", logo: "/retailers/amazon.svg" },
    { name: "Currys", logo: "/retailers/currys.svg" },
    { name: "Argos", logo: "/retailers/argos.svg" },
    { name: "Tesco", logo: "/retailers/tesco.svg" },
    { name: "Sainsbury's", logo: "/retailers/sainsburys.svg" },
    { name: "John Lewis", logo: "/retailers/johnlewis.svg" },
    { name: "Asda", logo: "/retailers/asda.svg" },
    { name: "AO.com", logo: "/retailers/ao.svg" },
];

// Stats for the hero section
export const stats = [
    { label: "Products Tracked", value: "500K+" },
    { label: "UK Retailers", value: "25+" },
    { label: "Price Updates", value: "Daily" },
    { label: "Price History", value: "5 Years" },
];
